# Setup
title:               Disruption and Discourse
tagline:             'Musings of a technician.'
description:         'All things data and analysis.'
url:                 http://j-delima.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jon Delima
  url:               http://j-delima.github.io
  email:             jon.r.delima@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
